### ISSUE TITLE
Exception: No submit queue specified

### ISSUE THREAD

**Issue by naumenko-sa** [amcpherson/citup#2]
Hello Andrew @amcpherson !

Thanks for developing citup!
I cannot run the default example:

```
(citup) $ run_citup_iter.py test.txt test.h5 --interactive --max_nodes 1
min_nodes: 1, max_nodes: 1
Traceback (most recent call last):
  File "/home/user/.conda/envs/citup/bin/run_citup_iter.py", line 4, in <module>
    __import__('pkg_resources').run_script('citup==0.1.0', 'run_citup_iter.py')
  File "/home/user/.conda/envs/citup/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/.conda/envs/citup/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/user/.conda/envs/citup/lib/python2.7/site-packages/citup-0.1.0-py2.7.egg/EGG-INFO/scripts/run_citup_iter.py", line 45, in <module>
    
  File "/home/user/.conda/envs/citup/lib/python2.7/site-packages/pypeliner/app.py", line 214, in __init__
    config_filename=self.config['submit_config'])
  File "/home/user/.conda/envs/citup/lib/python2.7/site-packages/pypeliner/execqueue/factory.py", line 6, in create
    raise Exception('No submit queue specified')
Exception: No submit queue specified
(citup)
```

Is it possible to run it in the current shell not sending jobs to the scheduler?

Thanks!
Sergey

**Comment by amcpherson** [comment]
Try --submit local

**Comment by naumenko-sa** [comment]
Thanks, it runs this way!
SN
