### ISSUE TITLE
Runing citup: pypeliner.scheduler - ERROR - exception

### ISSUE THREAD

**Issue by EsterAH89** [amcpherson/citup#7]
Hello, i'm running citup and getting an error for some of the input files, while it works for some others, so I do not think it is a problem of citup installation, or python version or etc. 
On the other side, could be a problem of the input files, however, all the input files look the same: txt file with 2 or more columns with numbers regarding mutation frequencies (see an example of input files on comments). The problem is that it worked for some of the input files and not for others without apparent reason. I have tried running it in cluster and locally. The code I'm running looks like this:

**run_citup_iter.py PATH_TO_INPUT_FILE/citup_input_1.txt  PATH_TO_OUTPUT_FILE/citup_output_1.h5 --submit local**

The error I got is this:

2023-07-25 16:49:13,628 - pypeliner.scheduler - ERROR - exception
	Traceback (most recent call last):
	  File "/miniconda/miniconda3/envs/citup_env/lib/python2.7/site-packages/pypeliner/scheduler.py", line 95, in run
	    self._wait_next_job(exec_queue, workflow)
	  File "/miniconda/miniconda3/envs/citup_env/lib/python2.7/site-packages/pypeliner/scheduler.py", line 195, in _wait_next_job
	    self._handle_error(job, received.log_text(), "failed to complete\n", exec_queue)
	  File "/miniconda/miniconda3/envs/citup_env/lib/python2.7/site-packages/pypeliner/scheduler.py", line 174, in _handle_error
	    raise pypeliner.graph.IncompleteJobException()
	IncompleteJobException
2023-07-25 16:49:13,629 - pypeliner.scheduler - ERROR - pipeline failed
log file: ./tmp/log/20230725-164836/pipeline.log
Traceback (most recent call last):
  File "/miniconda/miniconda3/envs/citup_env/bin/run_citup_iter.py", line 4, in <module>
    __import__('pkg_resources').run_script('citup==0.1.0', 'run_citup_iter.py')
  File "/miniconda/miniconda3/envs/citup_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/miniconda/miniconda3/envs/citup_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/miniconda/miniconda3/envs/citup_env/lib/python2.7/site-packages/citup-0.1.0-py2.7.egg/EGG-INFO/scripts/run_citup_iter.py", line 82, in <module>
    
  File "/miniconda/miniconda3/envs/citup_env/lib/python2.7/site-packages/pypeliner/app.py", line 260, in run
    self.sch.run(workflow, self.exec_queue, self.file_storage, self.runskip)
  File "/miniconda/miniconda3/envs/citup_env/lib/python2.7/site-packages/pypeliner/scheduler.py", line 113, in run
    raise PipelineException('pipeline failed')
pypeliner.scheduler.PipelineException: pipeline failed

Does anyone has a clue on what is happening??
I would really appreciate your help!!!

Rergards, 

Ester

**Comment by EsterAH89** [comment]
Here an example of one input file that rise an error:

0.9272	0.0141
0.9272	0.0141
0.0019	0.8817
0.9272	0.0141
0.0019	0.8817
0.9842	0.9488
0.0019	0.8817
0.0019	0.8817
0.0019	0.8817
0.0019	0.8817
0.0019	0.8817
0.0019	0.8817
0.9272	0.0141
0.9272	0.0141

**Comment by hanlu20221104** [comment]
Hi,@EsterAH89 Have you resolved this bug now? I also encountered the same problem.

**Comment by EsterAH89** [comment]
Hello @hanlu20221104 just realized that if you run the Citup QIP instead (check run_citup_qip.py -h) it works. In this case, you need to provide a table of mutation frequencies. 

More info here: https://github.com/amcpherson/citup

Hope it helps :)

**Comment by hanlu20221104** [comment]
Thanks for your reply @EsterAH89. I have used the command run_citup_qip.py, and the input files are freq.txt and clusters.txt, I still
 get pypeliner.scheduler.PipelineException: pipeline failed.

**Comment by SuqinYang** [comment]
Hi,@hanlu20221104 
Have you resolved this problem now? I encountered the same problem too.
